Connected users
do3-2021/dosm pull request #20
Opened 2022-02-19 16:26 UTC by Alexis-Bernard

Show all conneted users.
You can "ssh localhost" to test it.

2022-02-19 20:51 UTC, MathieuSoysal approved these changes

2022-02-20 12:09 UTC, RedbeanGit requested changes
Good job man il y a juste quelques petits trucs à régler et on pourra intégrer tes frames

2022-02-20 12:09 UTC, RedbeanGit commented on connected_users/frame.py
> +class frame(frame.DOSMFrame):
Il faut que tu nomme la classe `Tab`, pas `frame`

2022-02-20 12:09 UTC, RedbeanGit commented on connected_users/frame.py
> +        for column in columns.keys():
Ça marche mais tu peux utiliser `columns.items()` plutôt pour gagner du temps à l'avenir.
```python
for (name, display_name) in columns.items():
    self.datagrid.heading(name, text=display_name)
```

2022-02-20 12:09 UTC, RedbeanGit commented on connected_users/frame.py
> +            self.logger.write_log(users[len(users) - 1])
`users[len(users) - 1]` est équivalent à `users[-1]`. En utilisant des indices négatifs en Python, tu pars de la fin de la liste.

2022-02-20 12:09 UTC, RedbeanGit commented on connected_users/frame.py
> +    def hide(self):
Pense à implémenter cette méthode pour détruire les éléments de ton frame. `show()` est appelée à chaque fois que ton frame est montré et `hide()` a chaque fois qu'il est caché. Si tu n'implémente que `show()` alors tu risque de surcharger la mémoire.

2022-02-20 12:09 UTC, RedbeanGit commented on connected_users/mini_frame.py
> +        pass
Même chose ici du coup ^^

2022-02-20 12:55 UTC, MathieuSoysal requested changes

2022-02-20 12:55 UTC, MathieuSoysal commented on connected_users/frame.py
> +            self.logger.write_log(users[len(users) - 1])
Suggestion par rapport à la proposition de @RedbeanGit : [la proposition en question](https://github.com/do3-2021/dosm/pull/20/files/3c1b6b1d9877045c20d9fff076ef7bbb5e7bfd68#r810615131)
```suggestion
            self.logger.write_log(users[-1])
```

2022-02-20 12:55 UTC, MathieuSoysal commented on connected_users/frame.py
> +class frame(frame.DOSMFrame):
Suggestion par rapport à la proposition de @RedbeanGit : [la proposition en question](https://github.com/do3-2021/dosm/pull/20/files/3c1b6b1d9877045c20d9fff076ef7bbb5e7bfd68#r810614502)

```suggestion
class Tab(frame.DOSMFrame):
```

2022-02-20 12:55 UTC, MathieuSoysal commented on connected_users/frame.py
> +            self.datagrid.heading(column, text=columns[column])
Suggestion par rapport à la proposition de @RedbeanGit : [la proposition en question](https://github.com/do3-2021/dosm/pull/20/files/3c1b6b1d9877045c20d9fff076ef7bbb5e7bfd68#r810614823)

```suggestion
        for (name, display_name) in columns.items():
            self.datagrid.heading(name, text=display_name)
```

2022-02-20 17:41 UTC, Alexis-Bernard commented on connected_users/frame.py
> +class frame(frame.DOSMFrame):
Je renomme aussi le fichier frame.py --> Tab.py ?

2022-02-20 17:43 UTC, Alexis-Bernard commented on connected_users/frame.py
> +        for column in columns.keys():
Oh, effectivement, merci !

2022-02-20 17:44 UTC, Alexis-Bernard commented on connected_users/frame.py
> +            self.logger.write_log(users[len(users) - 1])
C'est fou ce qu'on peut faire avec python 👀

2022-02-20 17:55 UTC, Alexis-Bernard commented on connected_users/frame.py
> +    def hide(self):
ça marche, je vais modifier ça

2022-02-20 17:59 UTC, Alexis-Bernard commented on connected_users/frame.py
> +class frame(frame.DOSMFrame):
Fait !

2022-02-20 18:06 UTC, MathieuSoysal approved these changes

2022-02-20 22:59 UTC, RedbeanGit approved these changes
Ça me semble ok pour être intégré bien joué mec

2022-02-20 22:59 UTC, RedbeanGit commented
Je te laisse l'honneur de merger ta propre branche en cliquant sur `Merge pull request`

2022-02-20 23:12 UTC, merged