Cpu langlet
do3-2021/dosm pull request #21
Opened 2022-02-20 17:10 UTC by alexis-langlet

There is still some things I should correct (like the resizing with the window) but most of it should be ok and it's better not to merge everything the last day. 

Do not hesitate to make remarks on the code and implementation.

2022-02-20 23:30 UTC, RedbeanGit requested changes
Vu le nombre de fonctionnalités implémentées, tu t'en es vraiment bien sorti GG. Pour l'instant je pense que tu es celui qui a la plus grosse PR du projet.
Comme tu t'en doutais par contre il reste quelques trucs à régler avant de pouvoir intégrer ton module. A part ces modifs ça me semble ok good job ^^

2022-02-20 23:30 UTC, RedbeanGit commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
`psutil.cpu_percent()` est une fonction bloquante lorsqu'un intervalle différent de `0` ou `None` est défini. En laissant le code tel quel, on risque de faire freeze l'interface graphique. Pour pallier à ce problème je vois 3 solutions (de la plus simple à la plus complexe à mettre en place):
1. définir `interval=None` ou ne pas définir `interval` du tout (ce paramètre est optionnel).
2. rendre `update()` asynchrone à l'aide des mots clés `async` et `await`.
3. appeler `update()` sur un thread séparé.

2022-02-20 23:30 UTC, RedbeanGit commented on CPU/frame.py
> +from tkinter import *
Pas besoin d'importer tout `tkinter`, d'autant plus que certains objets présents dans ce module risquent d'entrer en conflit avec ton code

2022-02-20 23:30 UTC, RedbeanGit commented on CPU/frame.py
> +        scrollbar.grid(row=0, column=1, sticky=N+S)
Si tu veux faire en sorte que `tkinter` gère tout seul le redimensionnement de ton `dataTree` et de ta `scrollbar`, utilise `self.dataTree.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)` et `self.scrollbar.pack(side=tk.RIGHT, fill=tk.Y)` au lieu de `grid()`

2022-02-20 23:30 UTC, RedbeanGit commented on CPU/frame.py
> +        self.dataTree.grid(row=0, column=0, columnspan=1, sticky=N+S+E+W)
Tu peux supprimer cette ligne car tu place déjà ton `dataTree` dans la méthode `generateTreeView()`

2022-02-20 23:30 UTC, RedbeanGit commented on CPU/frame.py
> +        graphFrame.grid(row=0, column=2, sticky=N+S+E+W)
Pour laisser `tkinter` redimensionner ton `graphFrame` tu peux utiliser `graphFrame.pack(side=tk.BOTTOM, fill=tk.BOTH, expand=True)` au lieu de `grid()`

2022-02-20 23:30 UTC, RedbeanGit commented on CPU/frame.py
> +        self.after(1000, self.update, 1000) # every second...
La méthode `update(dt)` de ton frame est déjà automatiquement appelé toute les secondes par l'intégrateur. Tu peux donc retirer cette ligne pour éviter que ta méthode ne soit appelée 2 fois chaque seconde

2022-02-20 23:30 UTC, RedbeanGit commented on CPU/frame.py
> +    def update(self, dt):
Je crois que tu as oublié d'appeler la méthode `stats.update()` et `time.update()`. Corrige-moi si je me trompe

2022-02-21 00:48 UTC, MathieuSoysal commented on CPU/frame.py
> +        self.dataTree.grid(row=0, column=0, columnspan=1, sticky=N+S+E+W)
```suggestion
```

2022-02-21 00:50 UTC, MathieuSoysal commented on CPU/frame.py
> +        self.after(1000, self.update, 1000) # every second...
Pour faire suite à la proposition de @RedbeanGit :
```suggestion
```

2022-02-21 01:08 UTC, MathieuSoysal requested changes

2022-02-21 01:08 UTC, MathieuSoysal commented on CPU/frame.py
> +    def update(self, dt):
L'ingénieuse proposition formalisé de @RedbeanGit : 
```suggestion
    def update(self, dt):
       stats.update()
       time.update()
```

2022-02-21 01:08 UTC, MathieuSoysal commented on CPU/frame.py
> +from tkinter import *
Proposition de @RedbeanGit formalisé : 
```suggestion
```

2022-02-21 10:56 UTC, RedbeanGit commented on CPU/frame.py
> +    def update(self, dt):
Bien tenté mais ça ne marchera pas parce que `stats.update` prend un argument `stats` et `time.update` un argument `time`

2022-02-21 10:58 UTC, RedbeanGit commented on CPU/frame.py
> +        scrollbar.grid(row=0, column=1, sticky=N+S)
Il faut laissé `self.dataTree.configure(yscroll=scrollbar.set)`. Cette instruction permet de lier la scrollbar à son `dataTree`

2022-02-21 11:07 UTC, RedbeanGit commented on CPU/frame.py
> +from tkinter import *
Comme @alexis-langlet a importé le module `tkinter` sous le nom `tk`, il va falloir préfixer toutes les constantes importées à l'aide de `from tkinter import *` par `tk`.
Exemple: `BOTH` → `tk.BOTH`

2022-02-21 11:20 UTC, MathieuSoysal commented on CPU/frame.py
> +        scrollbar.grid(row=0, column=1, sticky=N+S)
Merci pour ton retour !
C'est bon j'ai corrigé la suggestion 👍

2022-02-21 17:12 UTC, alexis-langlet commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
Avec interval=None la valeur récupérée n'a aucun sens...
Je vais essayer de voir parmi les deux autres proposition ce qui semble le mieux, merci :+1:

2022-02-21 17:23 UTC, alexis-langlet commented on CPU/frame.py
> +    def update(self, dt):
Elles sont updates au moment de l'update de global_cpu donc normalement c'est ok ;) (c'est lui qui gère et contient tout donc je le laisse se charger des sous-logiques ;) )

2022-02-21 17:49 UTC, RedbeanGit commented on CPU/frame.py
> +    def update(self, dt):
Ah oui aux temps pour moi du coup problème réglé

2022-02-21 17:58 UTC, MathieuSoysal commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
Du coup c'est le dernier pas avant la merge ! :1st_place_medal:
Bon courage ! dernière ligne droite ! :octocat:

2022-02-21 18:33 UTC, alexis-langlet commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
j'ai opté pour la solution 2 mais je ne suis pas sûr à 100% que je le fais de la bonne façon...

2022-02-21 18:34 UTC, alexis-langlet commented on CPU/frame.py
> +        scrollbar.grid(row=0, column=1, sticky=N+S)
J'ai fait la modif mais ça ne s'auto-adapte toujours pas :thinking: Je creuserai la question plus en profondeur une prochaine fois, je ne pense pas que ce soit capital pour l'instant :)

2022-02-22 11:07 UTC, RedbeanGit commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
Avec `interval=None` psutil te renvoie l'utilisation en temps réelle du processeur, en pourcentage. J'ai testé de mon côté et les valeurs obtenues sont conformes à celles affichées dans mon moniteur système

2022-02-22 11:35 UTC, RedbeanGit requested changes
Comme tu utilise matplotlib, pense à ajouter cette dépendance dans `requirements.txt` à l'aide de 
```bash
pip3 freeze > requirements.txt
```

2022-02-22 11:35 UTC, RedbeanGit commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
Bien tenté mais simplement ajouter `async` ne suffit pas à rendre ta fonction asynchrone. `async` est utile lorsqu'il est utilisé avec des coroutines (équivalent des promesses) et le mot clé `await`. Sans `await` tout est synchrone dans ta méthode `update`.
Malheureusement, `psutil.cpu_percent` n'est pas une coroutine et ne peut donc pas être utilisé avec `await`.
Une solution pourrait être de créer une coroutine autour de `psutil.cpu_percent` qui notifie le système que cette fonction a terminé de s'executer mais ça serait un peu complexe à mettre en place.
Je pense que le plus simple reste de tout simplement supprimer `interval=None`. `psutil.cpu_percent` te retournera de cette façon l'utilisation instantanée du processeur (je viens de tester et j'obtiens des valeurs tout à fait cohérentes)

2022-02-22 11:35 UTC, RedbeanGit commented on CPU/tab_frame.py
> +        asyncio.run(self.cpu.update())
Du coup, pas besoin d'asyncio à moins que tu ne décides de créer une coroutine pour gérer l'attente d'une réponse de la part de `psutil.cpu_percent`. Dans ce cas, voici un lien qui devrait t'aider: https://stackoverflow.com/questions/41063331/how-to-use-asyncio-with-existing-blocking-library

2022-02-22 13:09 UTC, RedbeanGit commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
Il faudrait aussi que tu limites le nombre de données que tu ajoutes à ton graphique

2022-02-22 17:59 UTC, alexis-langlet commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
Ok effectivement, j'ai retesté et tu avais raison ça marche très bien avec interval=None, je ne sais pas pourquoi j'avais forcément 0 ou 100% la première fois que j'ai testé :thinking: 
Le fait est que du coup c'est corrigé, merci ;)

2022-02-22 17:59 UTC, alexis-langlet commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
nombre de données limité à 100 du coup

2022-02-22 18:02 UTC, alexis-langlet commented on CPU/cpu_data/global_cpu.py
> +        self.usages.append(psutil.cpu_percent(interval=0.5, percpu=False))
effectivement j'ai retesté et ça marche bien, je ne sais pas ce qu'il s'est passé la première fois. c'est corrigé du coup :)

2022-02-22 18:07 UTC, MathieuSoysal approved these changes

2022-02-22 18:10 UTC, MathieuSoysal requested changes

2022-02-22 18:10 UTC, MathieuSoysal commented on CPU/graph.py
> +        pass
@alexis-langlet Normal qu'il soit vide ?

2022-02-22 19:07 UTC, alexis-langlet commented on CPU/graph.py
> +        pass
ha non en effet, j'ai changé mais je ne vois pas trop l'interet du hide puisqu'on directement cacher nos frame depuis l'extérieur (vu qu'elles étendent des Frames de base)

2022-02-22 21:15 UTC, RedbeanGit commented on CPU/graph.py
> +        pass
En soi t'as le choix. Soit tu décide de créer une fois les widgets composants ta frame et après tu n'y touche plus, soit tu recrées le tout a chaque show et supprime tout a chaque hide.
Il n'y a pas de bonne ou de mauvaise façon de faire, ici ça dépend des cas de figures.

2022-02-22 21:19 UTC, RedbeanGit commented on CPU/graph.py
> +        pass
Par contre attention ! Les méthodes `show()` et `hide()` ne proviennent pas des `Frame` apportés par `tkinter` mais de la `BaseFrame` créée dans le package `integrator`

2022-02-22 21:23 UTC, alexis-langlet commented on CPU/graph.py
> +        pass
D'accord mais du coup, elle est censée faire quoi la fonction hide ?
Perso je l'ai juste utilisé comme alias d'une fonction qui sert à cacher la frame mais je vois pas trop l'interet...

2022-02-23 11:38 UTC, RedbeanGit requested changes
Dernière ligne droite il reste juste quelques petites lignes à changer et ça sera prêt pour l'intégration.
Est-ce qu'au passage tu peux renommer ton package `CPU` -> `cpu` pour garder une cohérence dans le nom des packages stp ?

2022-02-23 11:38 UTC, RedbeanGit commented on CPU/tab_frame.py
> +
Attention cette méthode est appelée à chaque fois que ton `TabFrame` est affiché donc un nouveau graphique et un nouveau tableau sont créés à chaque fois. Tu as donc 2 solutions:
1. Supprimer ton `dataFrame` et ton `graphFrame` dans la méthode `hide()`
2. Rajouter un `if self.shown:` et place le code `show()` dans ce `if`

2022-02-23 11:38 UTC, RedbeanGit commented on CPU/tab_frame.py
> +        self.after(1000, self.update, 1000)
Il faut que tu retire cette ligne sinon `update()` est appelé 2 fois a chaque fois et ça fait freeze l'interface. Ne t'inquiète pas l'intégrateur se charge d'update automatiquement ta `TabFrame`

2022-02-23 13:04 UTC, alexis-langlet commented on CPU/tab_frame.py
> +    def update(self, dt):
fait

2022-02-23 13:04 UTC, alexis-langlet commented on CPU/tab_frame.py
> +        self.after(1000, self.update, 1000)
Excuse moi, je la rajoute pour mes tests mais j'oublie systèmatiquement de l'enlever...

2022-02-23 13:05 UTC, alexis-langlet commented on CPU/tab_frame.py
> +
j'ai opté pour la solution 1

2022-02-23 14:04 UTC, RedbeanGit commented on CPU/graph.py
> +        pass
Mais dans le cas de `LineGraph`, pourquoi avoir créé une méthode `hide()` ?

2022-02-23 14:05 UTC, RedbeanGit commented on CPU/tab_frame.py
> +        self.after(1000, self.update, 1000)
No problem 😁

2022-02-23 16:42 UTC, alexis-langlet commented on CPU/graph.py
> +        pass
ha... c'est une erreur... et c'est corrigé

2022-02-23 19:04 UTC, RedbeanGit requested changes
Allez courage plus que quelques petits détails à régler

2022-02-23 19:04 UTC, RedbeanGit commented on cpu/summary_frame.py
> +        self.grid_forget()
`grid_forget` permet de supprimer ta `SummaryFrame` de la fenêtre. Le truc c'est que si ta `SummaryFrame` se supprime toute seule de la fenêtre, l'integrateur n'a aucun moyen de la replacer lors d'un show.
En fait dans la méthode `hide()` il faut uniquement que tu destroy les widgets qui se trouve dans ta `SummaryFrame`, pas la `SummaryFrame` elle même

2022-02-24 07:17 UTC, alexis-langlet commented
J'ai pris en compte tes dernière suggestion, normalement c'est réglé :)
Désolé que ce soit tant laborieux :sweat_smile:

2022-02-24 09:16 UTC, RedbeanGit requested changes
Juste 4 micro erreurs de tipo et on pourra merger.
Et t'inquiètes pas c'est normal de rencontrer des soucis, surtout dans un langage qui n'est pas habituel pour nous.
Pour limiter la casse je t'invite à toujours tout tester avant chaque push

2022-02-24 09:16 UTC, RedbeanGit commented on cpu/summary_frame.py
> +        super.show()
`super` -> `super()` (`super` est une fonction qui te retourne le ou les instances parente(s) de l'instance sur laquelle s'applique la méthode en cours)

2022-02-24 09:16 UTC, RedbeanGit commented on cpu/summary_frame.py
> +        super.hide()
Idem ici

2022-02-24 09:16 UTC, RedbeanGit commented on cpu/tab_frame.py
> +        super.show()
même chose

2022-02-24 09:16 UTC, RedbeanGit commented on cpu/tab_frame.py
> +        super.hide()
J'essaie de changer des "idem" et "même chose" mais je suis à cours d'idée haha

2022-02-24 12:38 UTC, alexis-langlet commented on cpu/summary_frame.py
> +        super.show()
c'est corrigé :)

2022-02-24 12:38 UTC, alexis-langlet commented on cpu/tab_frame.py
> +        super.hide()
:joy: idem c'est très bien XD

2022-02-24 18:27 UTC, RedbeanGit approved these changes
Ça y est on y est arrivé ! GG man

2022-02-24 18:32 UTC, MathieuSoysal approved these changes

2022-02-24 18:35 UTC, merged

2022-02-24 18:35 UTC, MathieuSoysal commented
Un incroyable merge pour un homme incroyable, félicitation à tous !

2022-02-24 19:00 UTC, alexis-langlet commented
Ca aura été long ! XD
Bravo à tous et merci pour votre patience :heart:

2022-02-24 19:02 UTC, alexis-langlet commented
Ca aura été long ! XD
Bravo à tous et merci pour votre patience :heart: